### ISSUE TITLE
Add option to prevent closing the modal on esc

### ISSUE THREAD

**Issue by cstriuli** [livewire-ui/modal#14]
Hey @PhiloNL ,

First of all, I wanted to say thanks for creating such a helpful package!

**Case**
I ran into a problem using the modal with a form with too many fields when accidentally pressed the "esc" button and lost all the information (yes.. I know 🤡).
So I thought it would be nice to add an option to prevent closing the modal when pressing esc or clicking outside. 
For example the property could be something like:

`clickToClose`: bool - default: `true`
If set to false, it will not be possible to close modal by clicking on the background or by pressing Esc key.

What do you think? I could create a PR with this feature,

Regards

**Comment by PhiloNL** [comment]
Hey @cstriuli,

Thanks for the kind words 🙏 
I have been there 🤡  haha, I'm looking into the modal width feature as well, they might share a similar approach towards setting custom modal properties. I'll see if I can add support for this as well. I'll get back to you next week 😄

**Comment by ultimateBusiness** [comment]
The option to prevent closing by clicking outside would be great as well ;-)

**Comment by PhiloNL** [comment]
@cstriuli this is now available 😄  add the following static method to your modal component

```php
public static function closeModalOnEscape(): bool
{
    return false;
}
```

**Comment by cstriuli** [comment]
🚀🚀🚀 Wow! how fast! thanks for implementing this feature

**Comment by sathio** [comment]
is it merged yet?

**Comment by PhiloNL** [comment]
@sathio yes, back in April 2021.

**Comment by anonymouse703** [comment]
@PhiloNL 

Why this not working in livewire? I tried to put it the list and form component even in the custom script.

```
public static function closeModalOnEscape(): bool
{
    return false;
}
```

Or I didn't put it right?
