### ISSUE TITLE
Error when update to 0.1.3

### ISSUE THREAD

**Issue by labomatik** [livewire-ui/modal#17]
After an update to 0.1.3 i've this error in alpine, i've published the php artisan vendor:publish --tag=livewire-ui:views to make sure all was ok but still have an error

```
Uncaught ReferenceError: modalWidth is not defined
    at eval (eval at d.el (alpine.js:144), <anonymous>:3:36)
    at d.el (alpine.js:144)
    at d (alpine.js:131)
    at f (alpine.js:139)
    at be.evaluateReturnExpression (alpine.js:1754)
    at T (alpine.js:673)
    at alpine.js:1717
    at Array.forEach (<anonymous>)
    at be.resolveBoundAttributes (alpine.js:1703)
    at be.initializeElement (alpine.js:1628)
```

**Comment by shuvroroy** [comment]
I checked and I didn't get any error from my end.

**Comment by jszobody** [comment]
Having the same issue here

**Comment by jszobody** [comment]
Copying the source of modal.js into my `public/vendor/livewire-ui folder` fixes the error for me. Seems the compiled js is perhaps not up to date?

And yes I did run `php artisan vendor:publish --tag=livewire-ui:public` and verified the compiled modal.js was updated.

**Comment by labomatik** [comment]
indeed copy pasting the content of `https://raw.githubusercontent.com/livewire-ui/modal/main/resources/js/modal.js` inside the public folder is correctly working

**Comment by chris-ware** [comment]
I had this issue and forcing the publish fixes it: `php artisan vendor:publish --tag=livewire-ui:public --force`

**Comment by PhiloNL** [comment]
Thanks for reporting! 
Forcing the publication of the script solves the problem. I'll update the documentation to reflect this. I'll look at an alternative method for loading the JS so this is not required.

**Comment by chris-ware** [comment]
> Thanks for reporting!
> Forcing the publication of the script solves the problem. I'll update the documentation to reflect this. I'll look at an alternative method for loading the JS so this is not required.

Might I suggest looking at how Livewire itself does this? As far as I know, the choice is optional whether you want to publish the files, but the `<livewire:scripts />` or `@livewireScripts` directives just work without any other user input.

**Comment by PhiloNL** [comment]
Thanks for the suggestion @chris-ware. I'll take a look.

**Comment by cntabana** [comment]
Thank you so much, Philo, for this plugin, before upgrading to 0.1.3 everything was working properly however after upgrading I need to click twice or more to make the modal appeared. In the console, I got this error message 

![modaljs](https://user-images.githubusercontent.com/6320126/116712040-584f9d80-a9cb-11eb-82cd-501d7e470c5f.png)

I have tried everything to fix it but none work.

Please any help will be appreciated.

**Comment by PhiloNL** [comment]
@cntabana this should be fixed in the latest version. Which version are you using?

**Comment by cntabana** [comment]
@PhiloNL I am using version 0.1.3

**Comment by PhiloNL** [comment]
> @PhiloNL I am using version 0.1.3

This is fixed in 0.1.4

**Comment by cntabana** [comment]
ok thank you

**Comment by cntabana** [comment]
It work, thank you
