### ISSUE TITLE
Missing security reporting details

### ISSUE THREAD

**Issue by io238** [livewire-ui/modal#21]
I'd like to report a security issue. Can you please add a policy and/or contact details? Thanks.

**Comment by PhiloNL** [comment]
Hi Martin,
Thanks for reaching out. If you can send me an email at me@philo.dev that would be perfect. Thanks!

**Comment by io238** [comment]
I've sent you an email. Thanks.

**Comment by PhiloNL** [comment]
Thanks Martin 🙏
