### ISSUE TITLE
Deployed via Forge - Requested an insecure script

### ISSUE THREAD

**Issue by oliverbj** [livewire-ui/modal#27]
Hi there

First of all, thank you very much for this awesome package. I really enjoy using it and it has saved me a lot of time!

I have some issues using the modals in production (on my server deployed by Laravel Forge). I encounter the following error:

> Mixed Content: The page at 'https://example.org/dashboard' was loaded over HTTPS, but requested an insecure script 'http://xx.xxx.xxx.xxx/vendor/livewire-ui/modal.js'. This request has been blocked; the content must be served over HTTPS.

Where `example.org` and `http://xx.xxx.xxx.xxx` should be replaced with my domain name and my server IP address. 

I am using LetsEncrypt (installed via Forge) to ensure SSL. However, I am not sure why livewire-ui/modal is connecting via `http`

**Comment by putera** [comment]
Try to use like this

 <script src="//xx.xxx.xxx.xxx/vendor/livewire-ui/modal.js" />

**Comment by oliverbj** [comment]
@putera I cannot change that specific line, as it is being specified in the [LivewireUIServiceProvider.php](https://github.com/livewire-ui/livewire-ui/blob/c6c1a108b1eabc16b1bc5b965074d81cf5dadc8a/src/LivewireUIServiceProvider.php#L27) file.

@PhiloNL Have you encountered this SSL issue on Forge?

**Comment by putera** [comment]
You can simply remove the @livewireUIScripts directive and add the script into your resources/js/app.js

`php artisan vendor:publish --tag=livewire-ui:scripts`

then add this to your resources/js/app.js

// Reference from published scripts

`require('./vendor/livewire-ui/modal');`

**Comment by oliverbj** [comment]
I see - thanks @putera! I'm just wondering if the official blade directive should be updated?

**Comment by PhiloNL** [comment]
I'm changing the way how this is loaded in a future release so this is no longer an issue.

**Comment by oliverbj** [comment]
I have applied a temp. fix, that forces `https://` (when using the `asset()` helper - which this package is using to load the script):

```php
//File: AppServiceProvider.php
public function register()
    {
        if(config('app.env') === 'production') {
            \URL::forceScheme('https');
        }
    }
```

**Comment by oliverbj** [comment]
@PhiloNL Was this ever changed? I would love to create a PR for it, but not quite sure what to change.

**Comment by PhiloNL** [comment]
@oliverbj not yet, I will introduce the change somewhere next week.

**Comment by PhiloNL** [comment]
@oliverbj changes will be released tomorrow but you can already give it a try: https://github.com/livewire-ui/modal/commit/13ddf19ba43529e8644186ff32f0cfdad57ee538

**Comment by PhiloNL** [comment]
v1 is now available and this issue has been resolved. See release notes for more information: https://github.com/livewire-ui/modal/releases/tag/1.0.0
