### ISSUE TITLE
i'm not sure issue is modal component but every time i got error when close modal

### ISSUE THREAD

**Issue by jouniikaheimo** [livewire-ui/modal#29]
Sometimes i got error Uncaught (in promise) DOMException: String contains an invalid character

if close or re-open modal ? 

any idea where and why that come ?

**Comment by cntabana** [comment]
Hi @jouniikaheimo , try to delete **public/vendor/livewire-ui/modal.js** and run this command **php artisan vendor:publish --tag=livewire-ui:public --force**

**Comment by PhiloNL** [comment]
Hi @jouniikaheimo 
Please include code samples, otherwise, it's difficult to help resolve the issue.
I'll re-open the issue once more information is provided.
