### ISSUE TITLE
Error since updating to 0.1.5

### ISSUE THREAD

**Issue by AlexJames-Dev** [livewire-ui/modal#30]
Hello,

Love the plugin, however since updating to version 0.1.5, i have the following issues in the console:

<img width="456" alt="Screenshot 2021-05-13 at 00 44 17" src="https://user-images.githubusercontent.com/43570309/118057849-aded5800-b384-11eb-9a0f-df295bc473c9.png">

I have run the command: php artisan vendor:publish --tag=livewire-ui:public --force

As per the documentation and deleted the modal.js file and re-run the command as was suggested by another user in an issue thread, still with no success. I tried manually adding in the function:

```
public static function closeModalOnClickAway(): bool
    {
        return true;
    }

```
as a temporary stopgap, however this did not work either! Let me know if you need any more info, ill be happy to supply what i can. 

Cheers

**Comment by thermiteplasma** [comment]
Did you previously publish the modal template via
```
php artisan vendor:publish --tag=livewire-ui:views
```

If so maybe try publishing again as the `closeModalOnClickAway` was added

**Comment by AlexJames-Dev** [comment]
> Did you previously publish the modal template via
> 
> ```
> php artisan vendor:publish --tag=livewire-ui:views
> ```
> 
> If so maybe try publishing again as the `closeModalOnClickAway` was added

Thanks for the advice, however that did not solve the issue im afriad. Republished the files which did not work, deleted the files in the resources and did a force publish, however the same issue still remains. Cheers.

**Comment by PhiloNL** [comment]
The way Javascript is loaded is going to be changed. See similar issue https://github.com/livewire-ui/modal/issues/27
