### ISSUE TITLE
how to use modal with livewire powergrid? 

### ISSUE THREAD

**Issue by luanfreitasdev** [livewire-ui/modal#33]
I recently added a feature to adapt the modal with powergrid

**`->openModal('edit-dish', ['dishId' => 'id']),`**
equals:
**`<button wire:click="$emit('openModal', 'edit-dish')">Edit</button>`**

`![action](https://user-images.githubusercontent.com/33601626/119275934-50f86a00-bbee-11eb-9409-6dc4d3965682.png)

EditDish:
![dish-modal](https://user-images.githubusercontent.com/33601626/119275888-037bfd00-bbee-11eb-80a2-3ad6242ba1dc.png)

View:
![view-modal](https://user-images.githubusercontent.com/33601626/119275912-39b97c80-bbee-11eb-9902-58b136f6f2f2.png)

Result:
![modal](https://user-images.githubusercontent.com/33601626/119275930-4b028900-bbee-11eb-80e4-25083898cac3.png)

Demo:
https://github.com/Power-Components/powergrid-demo

**Comment by PhiloNL** [comment]
Hi @luanfreitasdev 

What exactly is the issue that you are having?

**Comment by luanfreitasdev** [comment]
Hello, @PhiloNL .

I opened this issue just to say that it is possible to use your component with the powergrid.

thanks
