### ISSUE TITLE
 Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by omikronuk** [livewire-ui/modal#34]
This error happens whenever I click on a button to show the Modal. I am still able to see my modal though

app.js:252 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at Proxy.getActiveComponentModalAttribute (app.js:252)
    at Proxy.setActiveModalComponent (app.js:283)
    at app.js:355
    at  #MessageBus.js:17
    at Array.forEach (<anonymous>)
    at MessageBus.value (MessageBus.js:16)
    at Object.emit (Store.js:52)
    at index.js:306
    at Array.forEach (<anonymous>)
    at Component.value (index.js:296)
getActiveComponentModalAttribute @ app.js:252
setActiveModalComponent @ app.js:283
(anonymous) @ app.js:355
(anonymous) @ MessageBus.js:17
value @ MessageBus.js:16
emit @ Store.js:52
(anonymous) @ index.js:306
value @ index.js:296
value @ index.js:248
value @ index.js:7
(anonymous) @ index.js:58
Promise.then (async)
(anonymous) @ index.js:53
Promise.then (async)
value @ index.js:51
sendMessage @ index.js:221
value @ index.js:231
later @ debounce.js:8
setTimeout (async)
(anonymous) @ debounce.js:12
value @ index.js:204
(anonymous) @ Store.js:55
emit @ Store.js:54
value @ index.js:57
onclick @ dashboard:516

**Comment by PhiloNL** [comment]
Which version are you using and do you have some more code you can share?

**Comment by alslimany** [comment]
I am using `"livewire-ui/modal": "^0.1.5"` and facing the same issue.

**Comment by lvidal1** [comment]
Thanks for the awesome package. However, i am facing the same issue.

**Dependencies:**
```
"livewire-ui/modal": "^1.0",
"livewire/livewire": "^2.4",
```

**Blade snippet**
`<button onclick="Livewire.emit('openModal', 'modal.join-team')">Edit User</button>`

**Component**
```
<?php

namespace App\Http\Livewire\Modal;

use LivewireUI\Modal\ModalComponent;

class JoinTeam extends ModalComponent
{
    public function render()
    {
        return view('livewire.modal.join-team');
    }
}

```
**Error message:**

![image](https://user-images.githubusercontent.com/6495076/127699982-7461cad4-7f84-43cd-8bb1-8cc8cb0416eb.png)

**Comment by webtamizhan** [comment]
Hello @lvidal1 , please check your alpinejs version, i recommend you to use 
```
<!-- Alpine v3 -->
<script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
```
same error happened to me, it's gone after updating alpinejs version.

**Comment by f-liva** [comment]
Solved placing livewire scripts BEFORE alpine.js script

**Comment by ju5t** [comment]
@PhiloNL this issue appears on our current environment when switching to Vite. Webpack is fine. Reordering makes no difference, unfortunately. I'll let you know when I find more.

**Comment by SDJeff** [comment]
Same her after migrating to vite the modal is never opening L9.19 modal 1.06

**Comment by ju5t** [comment]
@SDJeff I found this is unrelated to this package. Other components we made ourselves have the same issue. It all boils down to `$wire` not being available.

I'm pretty sure this is related to Livewire and the ordering of things, so I've opened up https://github.com/livewire/livewire/discussions/5080.

**Comment by SDJeff** [comment]
Found solution for the existing L9 Project.
Need to update app.js (check at github repo to:
 
`import _ from 'lodash';
window._ = _;

/**
 * We'll load the axios HTTP library which allows us to easily issue requests
 * to our Laravel back-end. This library automatically handles sending the
 * CSRF token as a header based on the value of the "XSRF" token cookie.
 */

import axios from 'axios';
window.axios = axios;`

and delete old require entries for same modules. 

The Modal is running again.

**Comment by ju5t** [comment]
This was already changed in our application so this is not the issue for us.
