### ISSUE TITLE
Cannot read property '$wire' of undefined - Alpine Component inside modal

### ISSUE THREAD

**Issue by eckelarsson** [livewire-ui/modal#35]
Hello!

First of all, awesome package!!
When I try to use a component, in this case a toggle and want to entagle that to a property it can not read the $wire attribute.

The modal view file part

` <x-form.toggle class="mb-4" label="Annual billing" help="(Get 2 months free)" property="annual" />`

The component part

```
@props(['label', 'help', 'property'])

<div {{ $attributes->merge(['class' => 'flex items-center']) }} x-data="{ on: @entangle($property) }">
    <button type="button"
        class="relative inline-flex flex-shrink-0 h-6 transition-colors duration-200 ease-in-out bg-gray-200 border-2 border-transparent rounded-full cursor-pointer w-11 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-purple-500"
        aria-pressed="false" x-ref="switch" x-state:on="Enabled" x-state:off="Not Enabled" :class="{ 'bg-purple-600': on, 'bg-gray-200': !(on) }" aria-labelledby="annual-billing-label"
        @click="on = !on; @this.set('{{ $property }}', on)">
        <span class="sr-only">{{ $label }}</span>
        <span aria-hidden="true" class="inline-block w-5 h-5 transition duration-200 ease-in-out transform translate-x-0 bg-white rounded-full shadow pointer-events-none ring-0" x-state:on="Enabled"
            x-state:off="Not Enabled" :class="{ 'translate-x-5': on, 'translate-x-0': !(on) }"></span>
    </button>
```
When the modal tries to open i get the JS error

`index.js:31 Uncaught (in promise) TypeError: Cannot read property '$wire' of undefined`

**Comment by PhiloNL** [comment]
Hi @eckelarsson 
Thanks! Happy to hear that 😄 

I just tried adding `@entangle` to a blade component inside a modal and I don't get the `$wire` error.
What is the actual HTML which is returned? 

Because it should not call `$wire` but `Livewire`:

```
window.Livewire.find('fStzO4xs0FxauJdESCQm').entangle('your-property-name-here') }
```

**Comment by cntabana** [comment]
I have this issue too.

eg: you have a **date component** and you want to call it in modal you got that error:

**<div
    x-data="{ value: @entangle($attributes->wire('model')), picker: undefined }"
    x-init="new Pikaday({ field: $refs.input, format: 'MM/DD/YYYY', onOpen() { this.setDate($refs.input.value) } })"
    x-on:change="value = $event.target.value"
    class="flex rounded-md shadow-sm -ml-4 "
>
    <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 sm:text-sm">
        <svg class="h-5 w-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" clip-rule="evenodd" d="M6 2C5.44772 2 5 2.44772 5 3V4H4C2.89543 4 2 4.89543 2 6V16C2 17.1046 2.89543 18 4 18H16C17.1046 18 18 17.1046 18 16V6C18 4.89543 17.1046 4 16 4H15V3C15 2.44772 14.5523 2 14 2C13.4477 2 13 2.44772 13 3V4H7V3C7 2.44772 6.55228 2 6 2ZM6 7C5.44772 7 5 7.44772 5 8C5 8.55228 5.44772 9 6 9H14C14.5523 9 15 8.55228 15 8C15 7.44772 14.5523 7 14 7H6Z"/>
        </svg>
    </span>

    <input
        {{ $attributes->whereDoesntStartWith('wire:model') }}
        x-ref="input"
        x-bind:value="value"
        class="rounded-none rounded-r-md flex-1 form-input block w-full transition duration-150 ease-in-out sm:text-sm sm:leading-5"
    />
</div>**

error:

![error_modal](https://user-images.githubusercontent.com/6320126/121010633-90e25400-c78d-11eb-9d5a-2af8bb82ec8b.png)

**Comment by PhiloNL** [comment]
I'm unable to replicate this issue. I can further investigate if you provide a sample repository. Closing for now.

**Comment by cntabana** [comment]
Hi, I am sorry to reopen this issue.

I have tried to create a public repository where you can replicate this issue.

Repository: https://github.com/cntabana/modal

**This is the date component**: https://github.com/cntabana/modal/blob/main/resources/views/components/input/date.blade.php

**This the form**: https://github.com/cntabana/modal/blob/main/resources/views/welcome.blade.php

Please let me know if you want any further information

Thank you again

**Comment by nusoft** [comment]
Hi @cntabana 
Were you able to fix this issue? I get the same JS error when using `@entangle` inside a modal.

**Comment by edwinheij** [comment]
@cntabana @nusoft Did you have a solution to this? Got the same issue today. Thanks.
