### ISSUE TITLE
Tailwind production build

### ISSUE THREAD

**Issue by MarcelWeidum** [livewire-ui/modal#37]
When using tailwindcss as a package and building it with
```bash
npm run dev
```

Everything works fine. But when you want to only have the css of the classes been used and run
```bash
npm run prod
```

It is only showing the backdrop and not the modal because of some tailwind classes.

Purge property in `tailwind.config.js`:
```js
purge: [
    './resources/**/*.blade.php',
    './resources/**/**/*.blade.php'
],
```

**Comment by PhiloNL** [comment]
Hi @MarcelWeidum 
If you update your tailwind.config.js to include the modal blade file it should work:

```
module.exports = {
    purge: [
        './vendor/livewire-ui/modal/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],
}
```

**Comment by MarcelWeidum** [comment]
Hi Philo,

Thank you for the response. If I purge it with those settings the modal is not showing up with the production build.

![image](https://user-images.githubusercontent.com/9413586/120212121-eb316100-c231-11eb-88a1-59cfae388b7c.png)

**Comment by PhiloNL** [comment]
Hmm, that's strange. I use this myself without any issues. Any chance something else in your webpack/tailwind config is conflicting with the purge settings?

**Comment by MarcelWeidum** [comment]
I have a clean laravel app to check out this package. I have made de repo public so you can see the configs.

https://github.com/MarcelWeidum/test-wiremodal

**Comment by PhiloNL** [comment]
Thanks @MarcelWeidum 
This is indeed a bug, it's because of the dynamic width of the modal which prevents the purge hook from picking up the class.
I'll work on a fix for this. For now, if you just put the `sm:max-w-2xl` class (or other widths which you are using) anywhere in one of your blade files it will compile correctly.

**Comment by Akhmami** [comment]
same issue, i removed the modalMaxWidth() method and it worked fine, maybe this can be a temporary solution. I hope it will be fixed soon.

**Comment by Akhmami** [comment]
same issue, I upgraded to version v1.0.0 but it still doesn't change. finally, i removed modalMaxWidth() method and it works fine. I hope it will be fixed soon.

**Comment by JellyBool** [comment]
Anyone who come across this issue, I found a little trick to make it work. 

 ### Sulotion
Add a empty `<div>` to you layout file(`app.blade.php`), you can place it at the bottom right above `</body>` tag:

```html
<div class="sm:max-w-2xl sm:max-w-4xl hidden"></div>
```
Make sure your `<div>` classList match your `maxWith` defined in `modalMaxWidth()` method in your modal component:

```php
public static function modalMaxWidth(): string
{
    return '4xl'; // you should have `sm:max-w-4xl` in your empty div classList.
}
```

Hope it helps. @MarcelWeidum @Akhmami

**Comment by Akhmami** [comment]
thanks for responding @JellyBool, instead of giving an empty `<div>` containing the css properties, i prefer to add it in tailwind.config.js
```
purge: {
    // .......

   safelist: [
            'sm:max-w-2xl',
            'sm:max-w-sm'
    ]
}
```

**Comment by MarcelWeidum** [comment]
I added that with my pull request #42 which was references above here.
