### ISSUE TITLE
How to open the component modal itself? Not another component.

### ISSUE THREAD

**Issue by elfeffe** [livewire-ui/modal#39]
I want to instantiate my component, assigning a $model, and then I just want to open its own modal, not launching a new modal with a new component because the $model will be converted to Array.
Is it possible to open the modal on the component or it's obligatory to open another modal?

**Comment by PhiloNL** [comment]
Every time you open a modal with different parameters a new modal instance is created. 

For example, the following button will open a modal with $user being assigned the User model via type hinting:

```
<button onclick='Livewire.emit("openModal", "edit-user", {{ json_encode(["user" => $user->id]) }})'>Edit User</button>
```

When you open a modal from an existing modal, this will become a child modal.
If you don't want to open another modal, you just need to work with your existing component and don't use the `openModal` helpers:


```
// Component
public function changeModel($model)
{
   $this->currentModel = $model;
}

// Blade
{{ $currentModel }}
<button wire:click="changeModel('somethingElse')">Change model</button>
```
