### ISSUE TITLE
Livewire Inline Scripts

### ISSUE THREAD

**Issue by sotten** [livewire-ui/modal#40]
[Livewire Inline Scripts](https://laravel-livewire.com/docs/2.x/inline-scripts) does not work in a UI modal. Can anyone reproduce this error or have a solution?

**Comment by PhiloNL** [comment]
Please provide more info, step-by-step instructions on how to replicate, what you expect, what isn't working, code samples, etc.

**Comment by sotten** [comment]
@PhiloNL

I have created a [repository](https://github.com/sotten/modal). It is a simple Jetstream application with a Livewire component and a modal component. The interesting code is in this [commit](https://github.com/sotten/modal/commit/9f07442b480bff2c9a45d23a18b69960da92c78a).

I expect two console logs when I open the modal component:
"Modal is open"
"Push works"

The JavaScript is not loaded. Do I make a mistake?
