### ISSUE TITLE
Modal changing URL

### ISSUE THREAD

**Issue by Greenvold** [livewire-ui/modal#41]
Hello,

I am facing an issue that when i open the modal it changes my url of the page. Which is fine but it does not change it back on closure. Which leads to potential problems if users want to share link of the page or hit reload. Is there some solutions on that ? I am calling the modal from within another livewire component like this:

`  <button type="button" class="btn btn-primary"
            wire:click="$emit('openModal', 'backend.shared.media-item-selector')">{{__('components.media_item_selector.btn_text')}}</button>`

Upon opening the modal the url in browser changes to this:
![image](https://user-images.githubusercontent.com/56951790/120097464-e2a53180-c130-11eb-8a3e-c23d51ec806f.png)

Thank you!

**Comment by Greenvold** [comment]
I found out that this is an issue with using Livewire Pagination inside the modal.

My solution was to switch to classic pagination with customized pagination component. 

Do you think of some other solution how the livewire pagination would not affect the url?

**Comment by PhiloNL** [comment]
Pagination 'should' work but it sometimes can be a bit buggy. A PR was made to make it easier to work with pagination but it didn't make it, unfortunately. https://github.com/livewire/livewire/pull/1997
