### ISSUE TITLE
wire:loading.attr="disabled"  not working correctly with click event

### ISSUE THREAD

**Issue by eckelarsson** [livewire-ui/modal#43]
Hello!

Found a small glitch when using a button in the modal.

`<button type="submit" wire:click="test" class="text-white bg-black disabled:opacity-50" wire:loading.attr="disabled">Testing</button>`

It won't add the disabled attribute when wire:click is on the element, I tested it outside the modal as well and it worked as excepted.

The loding.class attribute won't work either, 

`wire:loading.class="pointer-events-none"`

**Comment by PhiloNL** [comment]
Hi @eckelarsson,
I'm unable to replicate this issue. Adding `wire:loading.attr="disabled"` works just fine for me.
If you can set up an example repository that replicates the issue you are having, I can investigate further.

**Comment by howdu** [comment]
@PhiloNL unforunetly it looks like this is still an issue. 

This example only the disabled attr is added to the 'Standard' button. 

```
<button wire:click="$emit('openModal', 'videos.create')" wire:loading.attr="disabled">
    Modal
</button>

<button wire:click="openModal" wire:loading.attr="disabled">
    Standard
</button>
```

**Comment by PhiloNL** [comment]
@howdu, that is correct; it doesn't work when emitting events. This is the expected behavior of Livewire.
