### ISSUE TITLE
Push script on modal

### ISSUE THREAD

**Issue by Krato** [livewire-ui/modal#45]
Hello, first thanks for this amazing package.

I'm having some troubles loading a custom livewire components. In that component I push some js to the layout. But when I call that component on a modal, the scripts are not being loaded, so the component doesn't work.

For example that simple function is not working:

```blade
@push('page-script')
    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", () => {
            console.log('test')
        })
    </script>
@endpush
```

How can I make it work?

**Comment by ottenso** [comment]
Ich habe das gleiche Problem, siehe #40

**Comment by ottenso** [comment]
Ich habe das gleiche Problem, siehe #40

**Comment by ottenso** [comment]
I have the same problem, see #40

**Comment by sotten** [comment]
Can't anyone help us?

**Comment by PhiloNL** [comment]
I don't think this is possible. The `DOMContentLoaded` event has already occurred because modals are loaded dynamically. Alpine seems to work fine, however:

```html
<!-- Inside a modal component -->
<div x-data="{}" x-init="alert('hello world')"></div>
```
