### ISSUE TITLE
[New Feature Request] ability to close child modal and refresh previous modal

### ISSUE THREAD

**Issue by 3alampro** [livewire-ui/modal#46]
Hello,

this feature request if possible can we have method on the controller to close a child modal and refresh previous modal 

or even close modal and refresh the Livewire component that opened it 

thanks for the great package today my first day using it and love it already

**Comment by thermiteplasma** [comment]
Have a look at the docs for the closeModalWithEvents method. You should be able to use this to refresh another modal or active livewire component.

**Comment by PhiloNL** [comment]
Hi @3alampro,

Happy to hear you love it already 😄 
You can simply emit events to refresh the previous modal like @thermiteplasma mentioned.
