### ISSUE TITLE
Modal does not work in a (private) package

### ISSUE THREAD

**Issue by gavinhewitt** [livewire-ui/modal#48]
I'm trying to use the modal from a private package but it seems they way Livewire-ui modal is set up, that's not possible. It seems that references to 'packagename::modal' do not work. Is this correct? And if so, is this something easily changed?

In Modal class you probably need to be able to set (not sure) something like:
```
$componentClass = app('packagename::livewire')->getClass($component);
```

And this somehow need to work too:
```
// Does not work
<button wire:click='$emit("openModal", "packagename::child-modal", @json(["name" => "Philo"]))' type="button">Open Child</button>
```

**Comment by PhiloNL** [comment]
Hi @gavinhewitt 

Please check bootstrap/livewire-components.php and verify the component name or verify the component name in your private package, you should have something like:

```php
class YourPackageServiceProvider extends ServiceProvider {
    public function boot() {
        Livewire::component('some-component', SomeComponent::class);
    }
}
```

Make sure the component name matches.

**Comment by gavinhewitt** [comment]
> Hi @gavinhewitt
> 
> Please check bootstrap/livewire-components.php and verify the component name or verify the component name in your private package, you should have something like:
> 
> ```
> class YourPackageServiceProvider extends ServiceProvider {
>     public function boot() {
>         Livewire::component('some-component', SomeComponent::class);
>     }
> }
> ```
> 
> Make sure the component name matches.

Thank you for making me look stupid! I indeed forgot to add the component to the serviceprovider ;-)
