### ISSUE TITLE
Modal does not open 

### ISSUE THREAD

**Issue by gavinhewitt** [livewire-ui/modal#49]
When I use the modal on a fresh Laravel install it works as expected, but when I try to integrate it into an existing project only the overlay/backdrop is visible. The modal itself does not launch. However, when I remove this (below) in devtools, it loads (but positioned incorrectly):

```
<span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">​</span>
```

Most likely there's something in my setup that causes this. I can't figure out what that is though, so could use some ideas on what to look for.

**Comment by sotten** [comment]
are they in the production environment? I had similar problems. My problem was due to Tailwind purge. See: https://github.com/livewire-ui/modal#building-tailwind-css-for-production

**Comment by gavinhewitt** [comment]
Hi, no, it's locally that I have this. I'm fairly sure I have set up Tailwind correctly :-(

**Comment by PhiloNL** [comment]
Seems like the issue @sotten mentioned. If it doesn't work when your run `npm run dev` it isn't related to the purge settings. Unfortunately, it's difficult to assist without the actual code from your existing project. Closing for now, feel free to re-open with additional code from your existing project.

**Comment by gavinhewitt** [comment]
Update: Works as expected when I add the component to the serviceprovider! (see issue https://github.com/livewire-ui/modal/issues/48)

Bedankt @PhiloNL !
