### ISSUE TITLE
One issue

### ISSUE THREAD

**Issue by jouniikaheimo** [livewire-ui/modal#5]
I have component Customer details. 
inside this button 
`<a href="#" onclick='Livewire.emit("openModal", "customer.edit-user", @json(["customer" => $customers->id]))' class="flex py-3 px-4 text-sm text-gray-700 hover:bg-gray-100 hover:text-gray-900" role="menuitem">`

that open modal fine

but `wire:click='$emit("openModal", "customer.edit-user", @json(["customers" => $customers->id])' `give error

 Unable to call component method. Public method [$emit("openModal", "customer.edit-user", {"customers":9}] not found on component: [customer.details]

**Comment by PhiloNL** [comment]
Hi @jouniikaheimo,

Could you add the contents of your blade file where the button is not working. It's a bit difficult for me to see what the issue could be based on the code you've shared. My first assumption is an issue with the quotes.

So the modal opens and you get that error or do you get this error when you click a button inside the modal?

Thanks!

**Comment by jouniikaheimo** [comment]
That error is coming try to open modal.

And that button is inside Details component 

```
<?php

namespace App\Http\Livewire\Customer;

use App\Models\Customer;
use LivewireUI\Modal\ModalComponent;

class Details extends ModalComponent
{

    public Customer $customers;

    public function render()
    {
        return view('livewire.customer.details', [
            'customers' => $this->customers
        ]);
    }
}
```
And i try to open modal where is edit-customer component

that is it working fine i call 

onclick='Livewire.emit("openModal", "customer.edit-user", @json(["customer" => $customers->id]))'

but wire:click method is better

**Comment by PhiloNL** [comment]
@jouniikaheimo  I think you might have forgotten a **")"** at the end:

`wire:click='$emit("openModal", "policy-edit", @json(["customers" => 1]))'`

Instead of 

`wire:click='$emit("openModal", "policy-edit", @json(["customers" => 1])'`

**Comment by jouniikaheimo** [comment]
That true :) but copy paste your document 

Passing parameters

To open the EditUser modal for a specific user we can pass the user id (notice the single quotes):


`<button onclick='Livewire.emit("openModal", "edit-user", @json(["user" => $user->id]))'>Edit User</button>`


`<button wire:click='$emit("openModal", "edit-user", @json(["user" => $user->id])'>Edit User</button>`


`<button wire:click='$emit("openModal", "edit-user", @json([$user->id, $isAdmin])'>Edit User</button>`


document missing too ) :D

**Comment by PhiloNL** [comment]
Updated the readme 😄  does it works for you now?

**Comment by jouniikaheimo** [comment]
Yes works fine :) thx help! and btw that component really awesome..

**Comment by PhiloNL** [comment]
Great! 😄  Thanks! 🙌
