### ISSUE TITLE
Form Submitted On Close Of Child Modal

### ISSUE THREAD

**Issue by amiyoghoshstar** [livewire-ui/modal#53]
Hello, 
First of all thanks for this awesome package. You made the developer's life easier.
Actually im having issues while closing the child modal. Child modal auto-submitted while closing. 

Screens
![Gif](https://s6.gifyu.com/images/desktop-1624116640626_1tOFlOfd_OgQv.gif)

If someone help me to solve this i will super chat him 5$ 
Just Kidding
 Thanks in advance..

**Comment by PhiloNL** [comment]
Hi @amiyoghoshstar
Without any code, it's difficult to determine the cause of this.
I suspect your close button may contain `type="submit`, changing this to `type="button"` would resolve the issue.

**Comment by amiyoghoshstar** [comment]
Hi, @PhiloNL thanks!! you are absolutely right!!
