### ISSUE TITLE
Exception from Interface thrown, when call from subdirectory

### ISSUE THREAD

**Issue by locopine** [livewire-ui/modal#54]
An exception is thrown when calling a component in subdirectories.
(Ex.  

`php artisan make:livewire Register/create`

```
<button wire:click="$emit('openModal','register.create')"
        class="bg-indigo-500">
    {{ __('New Register) }}
</button>
```

> Exception
> [App\Http\Livewire\Register\Create] does not implement 
> [LivewireUI\Modal\Contracts\ModalComponent] interface.)

**Comment by PhiloNL** [comment]
This is not related to subdirectories, you need to make sure you extend the `LivewireUI\Modal\ModalComponent` class.

**Comment by locopine** [comment]
I am sure that I have faithfully followed the documentation. However, several times, you submitted the exception!

I restarted the PC and finally the behavior disappeared.

Anyway, thank you very much for your attention.

**Comment by PhiloNL** [comment]
Hi @locopine 
Happy to hear the issue is resolved 😄
