### ISSUE TITLE
Unable to locate publishable resources

### ISSUE THREAD

**Issue by milanchheda** [livewire-ui/modal#57]
Hey,

Thanks for the awesome package. 

When running `php artisan vendor:publish --tag=livewire-ui-modal-views`, its throwing an error `Unable to locate publishable resources`

I see the following when running `php artisan vendor:publish`: 

```
Tag: livewire-ui:public
Tag: livewire-ui:scripts
Tag: livewire-ui:views
```

Seems `livewire-ui-modal-views` is missing.

**Comment by PhiloNL** [comment]
Hi @milanchheda,
Can you verify you are on the latest version? (`v1.1`)

**Comment by milanchheda** [comment]
```"livewire-ui/modal": "^0.1.7"```

Ok, I will try updating to `1.0`.

Thanks.
