### ISSUE TITLE
Data type issue 

### ISSUE THREAD

**Issue by Theraen** [livewire-ui/modal#58]
Hey,
I want to be able to access the methods of my User instance from my modal. I do send a User object to my modal, except that it transforms my object into an array.

The code to open my modal :

![image](https://user-images.githubusercontent.com/1116725/124768063-a4254280-df38-11eb-9a9c-5269cf3ca7da.png)

$row contains the User object :

![image](https://user-images.githubusercontent.com/1116725/124768107-af786e00-df38-11eb-82fa-508d9dd09276.png)

However, once I click on the button to open the modal, it tells me that I am sending an array and its waiting for an instance of the User class

![image](https://user-images.githubusercontent.com/1116725/124768181-bc955d00-df38-11eb-8701-fae0506200cc.png)

The code of my livewire controller :

![image](https://user-images.githubusercontent.com/1116725/124768215-c323d480-df38-11eb-86b4-c79c25f19d9d.png)

I provide you with the stack trace of my error
[https://flareapp.io/share/lm2G0YAP#F61](https://flareapp.io/share/lm2G0YAP#F61 )

Thank you for your help !

**Comment by PhiloNL** [comment]
Hi @Theraen
You will need to send the ID instead of the entire object.

`$emit('openModal', 'edit-user', {{ json_encode(['user' => $user->id]) }})`

You might also, need to change the public property to if you get an invalid type error:

`public string|User $user;`

**Comment by danielreales7** [comment]
> Hi @Theraen
> You will need to send the ID instead of the entire object.
> 
> `$emit('openModal', 'edit-user', {{ json_encode(['user' => $user->id]) }})`
> 
> You might also, need to change the public property to if you get an invalid type error:
> 
> `public string|User $user;`

Hi @PhiloNL I have the same issue.

I open a modal with users. Every column have edit buton with this:

wire:click='$emit("openModal", "modals.colaboradores-editar", {{ json_encode(["colaborador" => $colaborador->id]) }})'

![image](https://user-images.githubusercontent.com/5383214/126160891-5537a016-8f72-4bb3-91be-94a96af4d9f4.png)

![image](https://user-images.githubusercontent.com/5383214/126160966-07fc0e49-077d-4722-86b0-a588cccb630e.png)

![image](https://user-images.githubusercontent.com/5383214/126161066-67e07754-2e4e-4807-84bf-2e48b5464ffa.png)

**Comment by PhiloNL** [comment]
@danielreales7 update`public Colaborador $colaborador;` to `public Colaborador | int $colaborador;`;

**Comment by danielreales7** [comment]
> @danielreales7 update`public Colaborador $colaborador;` to `public Colaborador | int $colaborador;`;

I try this but I have errors: 

![image](https://user-images.githubusercontent.com/5383214/126183536-0ba5499f-c602-44c0-a3fb-382545e0cc50.png)

**Comment by wlhrtr** [comment]
Bit of an older issue but ran into same issue.

I have overritten the `Modal.php`

```
use App\Extension\Modal as ExtensionModal;
use Illuminate\Foundation\AliasLoader;
use Illuminate\Support\ServiceProvider;
use LivewireUI\Modal\Modal;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $loader = AliasLoader::getInstance();
        $loader->alias(Modal::class, ExtensionModal::class);
    }

}
```

In `Modal.php` i added this part to `openModal()` function.

```
$componentAttributes = collect($componentAttributes)
            ->merge($this->resolveComponentProps($componentAttributes, new $componentClass))
            ->all();
```

And finally added and adapted some function from Livewire and added them to my own `Modal.php`

```
public function resolveComponentProps(array $attributes, Component $component)
    {
        if (PHP_VERSION_ID < 70400) {
            return;
        }

        return $this->getPublicPropertyTypes($component)
            ->intersectByKeys($attributes)
            ->map(function ($className, $propName) use ($attributes) {
                $resolved = $this->resolveParameter($attributes, $propName, $className);

                return $resolved;
            });
    }

    protected function resolveParameter($attributes, $parameterName, $parameterClassName)
    {
        $parameterValue = $attributes[$parameterName];

        if ($parameterValue instanceof UrlRoutable) {
            return $parameterValue;
        }

        $instance = app()->make($parameterClassName);

        if (!$model = $instance->resolveRouteBinding($parameterValue)) {
            throw (new ModelNotFoundException())->setModel(get_class($instance), [$parameterValue]);
        }

        return $model;
    }

    public function getPublicPropertyTypes($component)
    {
        if (PHP_VERSION_ID < 70400) {
            return new Collection();
        }

        return collect($component->getPublicPropertiesDefinedBySubClass())
            ->map(function ($value, $name) use ($component) {
                return Reflector::getParameterClassName(new \ReflectionProperty($component, $name));
            })
            ->filter();
    }
```


Now I can add my typed property to my Modal like so:

```
class Create extends ModalComponent
{
    public Device $device;
}
```
And Modal.php will resolve my Model and add it to the livewire component.
Livewire will care about keeping the Model in the 'state'.

Property in `openModal()` call in blade and property in component must have the same name.
Value of `openModal()` must be the ID of the model.
