### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of undefined

### ISSUE THREAD

**Issue by oliverbj** [livewire-ui/modal#59]
Hi there!

I am using Turbolinks together with this package, so not sure if you are able to assist, but I thought I would ask anyways..

When triggering any modal (and when Turbolinks is enabled), i get the below error (the modal does open however):

 > Uncaught TypeError: Cannot read property 'querySelector' of undefined at modal.js:103

More specifically, this line (103):

> var focusable = _this.$refs[id].querySelector('[autofocus]');

If I either:
 - Do a manual page refresh
 - Disable Turbolinks

The error does not appear. I guess this is something to do with how Turbolinks acts (and does not refresh the page normally)?

Just wanted to see if anyone was able to help me with a solution, as I would like to keep Turbolinks on my website.

**Comment by heat23** [comment]
Help! Also seeing similar error when upgrading from Alpine V2 -> V3 and livewire/ui-modal 1.0
`cdn.min.js:1 Uncaught TypeError: Cannot read property 'querySelector' of undefined
    at general:826
    at ge (cdn.min.js:5)
    at cdn.min.js:5
    at m (cdn.min.js:1)
    at cdn.min.js:5
    at cdn.min.js:5
    at Object.<anonymous> (cdn.min.js:5)
    at Object.cancel (cdn.min.js:5)
    at wr (cdn.min.js:5)
    at Object.in (cdn.min.js:5)`

**Comment by PhiloNL** [comment]
Hi there! I'm not sure what the issue could be, I don't use Turbolinks unfortunately. I'm closing this issue but if you have found a solution that requires changes, be sure to reach out.

**Comment by NickJorens** [comment]
I'm getting the same issue. I'm trying to open a child modal. 
The child modal works great on a different page where it's the first modal. I thus only have an issue when it's a child modal.

**Comment by NickJorens** [comment]
Could you REOPEN please?

**Comment by NickJorens** [comment]
I managed to fix the issue! :tada: 
It was due to 2 AlpineJS errors. I had 2 blade components that use javascript plugins (imask and pikaday). I had to init them on the nexttick in order to have them load correctly, this caused some cascading errors.

Pikaday example:
```` 
x-data="{ value: @entangle($attributes->wire('model')), picker: undefined }"
x-init="$nextTick(() => {
    new Pikaday({ field: $refs.input, format: '{{ $format }}', onOpen() { this.setDate($refs.input.value);  } });
})"
x-on:change="value = $event.target.value"
````
