### ISSUE TITLE
Open modal from simple livewire component

### ISSUE THREAD

**Issue by lava83** [livewire-ui/modal#61]
Hi, is there a simple way to fire the `emitTo` in a simple livewire component class? 

This: 

```php
$this->emitTo('my-message-modal-component', 'openModal', __('FooBar'));
```

didnt work for me?

**Comment by PhiloNL** [comment]
You need to use `emit` instead of `emitTo`:
```php
$this->emit('openModal', 'edit-user', json_encode(["user" => $user->id])
```

**Comment by lpoirothattermann** [comment]
> You need to use `emit` instead of `emitTo`:
> 
> ```
> $this->emit('openModal', 'edit-user', json_encode(["user" => $user->id])
> ```

Hello, can you explain why we not to use `emit` instead of `emitTo` ? I don't get it
