### ISSUE TITLE
Modal or plain blade component

### ISSUE THREAD

**Issue by labomatik** [livewire-ui/modal#64]
Is there any way to handle the livewire component in modal or normal livewire componant
Currently i've a customer detail but i would like to display in a blade component as simple detail but also would like to open it as model in other part of the website.

Thanks for your help.

**Comment by labomatik** [comment]
I did some experimentation and it seems that adding  ```extends ModalComponent``` doesn't impact using the livewire component as a simple ```<livewire:XXXX />```
Nevertheless, i would be happy to have some advice if it's good or not :-)

**Comment by thermiteplasma** [comment]
Not sure if this is the best approach but I've had a similar circumstance where I just used the @include blade directive to share view stuff and a trait to share logic.

**Comment by PhiloNL** [comment]
> I did some experimentation and it seems that adding `extends ModalComponent` doesn't impact using the livewire component as a simple `<livewire:XXXX />`
> Nevertheless, i would be happy to have some advice if it's good or not :-)

You can definitely take that approach but I can't guarantee this will introduce problems in the future 😇
