### ISSUE TITLE
404 Not found returned when used outside livewire

### ISSUE THREAD

**Issue by mohamedsabil83** [livewire-ui/modal#66]
The package works like a charm when called inside livewire component:
```blade
wire:click="$emit('openModal', 'frontend.photo-display', {{ json_encode(['photo' => $photo->id]) }})"
```

But when called from normal blade it returns 404:
```blade
onclick="Livewire.emit('openModal', 'frontend.photo-display', {{ json_encode(['photo' => $photo->id]) }})"
```
 
Am I missing something?

**Comment by PhiloNL** [comment]
Is the modal returning a 404? Or are you redirect to a page and get a 404?

**Comment by mohamedsabil83** [comment]
Yes, the modal return 404

**Comment by PhiloNL** [comment]
I would recommend doing a `dd` from the modal mount method and see if the photo is being passed as the attribute.

**Comment by mohamedsabil83** [comment]
I tried that but when clicking the button it returns 404 as shown in this image:

![Screenshot from 2021-07-18 15-02-36](https://user-images.githubusercontent.com/10126040/126066294-80a4a15b-a647-417d-b93e-b7de008a3adc.png)

It works when I used it inside the livewire component but not from blade with general JS call it returns the above 404 error.

**Comment by PhiloNL** [comment]
I can't replicate this issue, so I'm closing this for now. If you can create a repository and replicate this issue, let me know, and I'll investigate further.

**Comment by mohamedsabil83** [comment]
I'll make more tests and reply when I found the problem.
