### ISSUE TITLE
Weird quote marks thing on livewire refresh

### ISSUE THREAD

**Issue by seabasss** [livewire-ui/modal#68]
Thanks for a great package! :)

Running into a weird thing where quote marks gets screwed up after a livewire refresh.

So a json string starts out looking something like this in the browser:
`<x-button wire:click="$emit('openModal', 'update', {"rowId":1})" />`

After a livewire refresh it looks like this in the browser:
`<x-button wire:click="$emit('openModal', 'update', {" />`

I guess it's trying to close the `wire:click="xxx"` with the first quote mark of the json string and not return anything after that.
I tried using single quotes in `wire:click='xxx'`, but then I got weird unexpected END IF problems with my button component.

My current solution is the following but there must be a better way :D
`<x-button wire:click="$emit('openModal', 'update', {{ str_replace('&quot;', '\'', e(json_encode(['rowId' => $rowId]))) }})" />`

Thank you!

**Comment by PhiloNL** [comment]
Switching to single quotes will fix this issue I believe:

```
<x-button wire:click='$emit("openModal", "update", {"rowId":1})' />
```

**Comment by seabasss** [comment]
Thanks!

That gives me `syntax error, unexpected token "endif", expecting end of file`

When I run `<x-button wire:click='$emit("openModal", "edit", {{ json_encode(['id' => $rowId]) }})'>Edit</x-button>`

An error that I don't get with double quotes.

This gives no erors, but then I don't get my parameter:
``<x-button wire:click='$emit("openModal", "edit">Edit</x-button>``

Ideas? Thanks!
