### ISSUE TITLE
Second parameter to closeModalWithEvents()?

### ISSUE THREAD

**Issue by seabasss** [livewire-ui/modal#70]
Is there any way I can do this with `closeModalWithEvents()`?

```
$this->emit('deletePost', $this->post->id);
$this->closeModal();
```

This doesn't seem to work, since it's expecting an array:
`$this->closeModalWithEvents('deletePost', $this->post->id);`

**Comment by PhiloNL** [comment]
This should do the trick:
```php
$this->closeModalWithEvents(['deletePost' => $this->post->id]);
```

**Comment by seabasss** [comment]
Thank you!

Unfortunately it doesn't seem to work. `deletePost` is not triggered.

What I need and what is working:

```
$this->emit('deletePost', $this->post->id);
$this->closeModal();
```

Result:

![Working](https://user-images.githubusercontent.com/5251896/127394906-17dc7fee-33e4-4957-8042-073a365826a9.png)

Not working:
```
$this->closeModalWithEvents(['deletePost' => $this->post->id]);
```

Result:

![Not Working](https://user-images.githubusercontent.com/5251896/127395001-030561b0-0c8f-4846-8177-8d9e30294918.png)

I mean, not the end of the world to do the first option, but it's a little cleaner with all in one if possible.

Thank you!

**Comment by tailorbuilt** [comment]
I may be missing something entirely.  

` $this->closeModalWithEvents(['returnMasterName' => $master_name_id]);`
or
`        $this->emit('returnMasterName', $master_name_id);
        $this->closeModal();`

Using both of the above methods, I get the same error back:

`ErrorException
Attempt to read property "fullname" on int (View: /Users/treaves/Development/projects/tbhub/resources/views/livewire/mni/master-name-search.blade.php)
`
what is strange, master-name-search is the child modal that I am executing the command.  It was opened by "rim-person-form", which is also a modal.
"returnMasterName" is being listened for on "rim-person-form" (RimPersonForm), but I never get anything back on it.

RimPersonForm:
`<?php

namespace App\Http\Livewire\Rim;

use App\Models\Person_type;
use App\Models\rim_admin;
use App\Models\rim_person;
use LivewireUI\Modal\ModalComponent;
use Log;

class RimPersonForm extends ModalComponent
{
    protected $listeners = [
        'updateField' => 'updateField',
        'openMasterName' => 'openMasterName',
        'returnMasterName' => 'returnMasterName'
    ];

    public $rim_admin_id;
    public $person_id;
    public $master_name_id;
    public $last_name;
    public $first_name;

    public $person_types;
    public $mode;

    public function mount(rim_person $rim_person, rim_admin $rim_admin)
    {
        $this->person_types = Person_type::all();

...
    }
    public function render()
    {
        return view('livewire.rim.rim-person-form');
    }

    public function openMasterName()
    {
        $last_name = $this->last_name;
        $first_name = $this->first_name;


        $params = [
            'screen' => 'rim-person-form',
            'last_name' => $last_name,
            'first_name' => $first_name,
  
        ];

        $this->emit('openModal', 'mni.master-name-search', [$params]);
    }

    function returnMasterName($master_name_id)
    {
        $this->master_name_id = $master_name_id;
        $this->first_name = $master_name_id;
    }

    public static function closeModalOnClickAway(): bool
    {
        return false;
    }
    public static function closeModalOnEscape(): bool
    {
        return false;
    }

    public static function modalMaxWidth(): string
    {
        return '6xl';
    }
}
`

MasterNameSearch:
`<?php

namespace App\Http\Livewire\Mni;

use App\Http\Livewire\Rim\RimPersonForm;
use App\Models\MasterName;
use Livewire\WithPagination;
use LivewireUI\Modal\ModalComponent;

class MasterNameSearch extends ModalComponent
{
    //    protected $listeners = ['returnScreen' => 'returnScreen'];

    public $screen;
    public $last_name;
    public $first_name;
    public $ssno;
    public $dlno;
    public $state_id;
    public $other_id;

    public $results;

    use WithPagination;

    public function mount(array $params)
    {
        $params = (object) $params;
        $this->screen = $params->screen;
        $this->last_name = $params->last_name;
        $this->first_name = $params->first_name;


        //        Log::debug(print_r($params, true));

        $master_name = MasterName::latest();
        if ($this->last_name != '') {
            dump('inside last name..');
            $master_name->where(
                'last_name',
                'like',
                '%' . $this->last_name . '%'
            );
        }
        if ($this->first_name != '') {
            dump('inside first name..');
            $master_name->where(
                'first_name',
                'like',
                '%' . $this->first_name . '%'
            );
        }
        $this->results = [$master_name->orderBy('last_name')->paginate(10)];
    }

    public function render()
    {
        return view('livewire.mni.master-name-search');
    }

    public function ReturnBack($master_name_id)
    {
        //        $this->closeModalWithEvents(['returnMasterName' => $master_name_id]);
        $this->emit('returnMasterName', $master_name_id);
        $this->closeModal();
    }

    public static function closeModalOnClickAway(): bool
    {
        return false;
    }
    public static function closeModalOnEscape(): bool
    {
        return false;
    }

    public static function modalMaxWidth(): string
    {
        return '6xl';
    }
}
`
