### ISSUE TITLE
Struggling to use wire:click on modals

### ISSUE THREAD

**Issue by xitude** [livewire-ui/modal#72]
Hello,
Got a modal with the following method inside the `extended ModalComponent`.

```
public function confirm()
    {
        dd('here');
    }
```
But when I click on the `<button wire:click="confirm"></button>` I get the following error.

```
Unable to call component method. Public method [confirm] not found on component: [livewire-u-i.modal.modal]
```

I saw the `not found on component: [livewire-u-i.modal.modal]` part and tried to emit on the `wire:click="$emit('confirm', 'dashboard.purchase.single.confirm')"` but this got me nowhere.

Thanks in advance for any support.

**Comment by PhiloNL** [comment]
Hello,
I'm unable to replicate this issue.
I can further investigate if you provide me with an example repository containing the code (fresh installation of Laravel, Livewire, and Livewire UI modal) required to replicate the issue.

**Comment by arwanfiles** [comment]
Same issue here.
Solved for me by [this](https://github.com/wire-elements/modal/issues/8#issuecomment-1124595582)

**Comment by Trevor-crypto243** [comment]
Same here
