### ISSUE TITLE
Livewire UI Modal vs Jetstream Modal

### ISSUE THREAD

**Issue by AlexioVay** [livewire-ui/modal#73]
Does anyone here have experience with both modal systems? If I'm using Jetstream should I use the built in Jetstream modal or does Livewire UI Modal have more advantages (or vice versa)?

**Comment by PhiloNL** [comment]
Livewire UI Modal allows you to launch any modal from anywhere, open child modals, pass parameters, maintain state, interact with other Livewire components, etc. whereas Jetstream is a more static approach where you must include the modal on the page itself and build your own implementation to open multiple modals, support child modals etc.
