### ISSUE TITLE
same issue, I upgraded to version v1.0.0 but it still doesn't change. finally, i removed modalMaxWidth() method and it works fine. I hope it will be fixed soon.

### ISSUE THREAD

**Issue by Akhmami** [livewire-ui/modal#74]
same issue, I upgraded to version v1.0.0 but it still doesn't change. finally, i removed modalMaxWidth() method and it works fine. I hope it will be fixed soon.

_Originally posted by @Akhmami in https://github.com/livewire-ui/modal/issues/37#issuecomment-887665695_

**Comment by JellyBool** [comment]
@Akhmami  Try the solution here https://github.com/livewire-ui/modal/issues/37#issuecomment-895188137
