### ISSUE TITLE
Is there an option to find out if the modal was just closed?

### ISSUE THREAD

**Issue by AlexioVay** [livewire-ui/modal#76]
I'm opening modals with a url hash like `#register` to quickly open up the register form. However, I can't reopen the modal when the hash persists and therefore I want to find out if I can detect if a modal has just been closed?

**Comment by PhiloNL** [comment]
@AlexioVay yes, this was added in 0.1.6, see the following link for more information: https://github.com/livewire-ui/modal/releases/tag/0.1.6

**Comment by AlexioVay** [comment]
Thank you! But how/where can I get or listen to this modalClosed event? Can you give me a code example in Vanilla JS?

**Comment by PhiloNL** [comment]
@AlexioVay you can use ```
Livewire.on('modalClosed', function(componentName) {
});
```
