### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by webtamizhan** [livewire-ui/modal#77]
Hello @PhiloNL , 

Thanks for the amazing package!

I am using 

Laravel v8.53.0
Livewire v2.5.5
Livewire UI Modal v1.0.0

I am facing issue while opening modal from modal component.

`
$this->emit('openModal', 'admin.assignment.confirm-move-subscription',
 json_encode([
            'assignment_id' => $this->assignment->id,
            'selectedCustomerID' => $this->selectedAccount,
            'selectedCompany' => $this->selectedCompany,
            'type' => $this->sub_type
        ]));
`

`Illuminate\Contracts\Container\BindingResolutionException
Unable to resolve dependency [Parameter #0 [ <required> $assignment_id ]] in class App\Http\Livewire\Admin\Assignment\ConfirmMoveSubscription`

**Comment by PhiloNL** [comment]
Hi @webtamizhan,
Unfortunately, it's difficult for me to assist without having code to investigate.
If you could set up a fresh Laravel install, replicate the issue, and share this repository with me that would be great.

**Comment by webtamizhan** [comment]
Sorry, It's my mistake by using json_encode on ModalComponent while emitting caused the `Unable to resolve dependency`.

Now issue got fixed.

Thanks for your reply @PhiloNL .
