### ISSUE TITLE
Disable the button that is clicked to open the modal

### ISSUE THREAD

**Issue by indiandollar** [livewire-ui/modal#79]
I have looked around and have not been able to find the option to disable the button that is clicked to open the modal while it's loading. I have tried using `wire:loading` and it's not working. It should be working with `wire:loading` because eventually, livewire is making the same request to the backend to fetch the component data.

**Comment by PhiloNL** [comment]
I think the `wire:loading` property is scoped to a given component. You might be able to define your own logic by using the Javascript hooks: https://laravel-livewire.com/docs/2.x/lifecycle-hooks
