### ISSUE TITLE
Events not work

### ISSUE THREAD

**Issue by alighasemzadeh** [livewire-ui/modal#80]
Hi
I have one ToDoList and I want to refresh tasks after adding new task.
Please check my application and guide me to solve this problem.
https://github.com/alighasemzadeh/dolist/blob/a7598ef1160da3e5f607d02f6a53fb64d9848fce/app/Http/Livewire/Task/Create.php#L29

**Comment by pwncraft** [comment]
In your App\Http\Livewire\Dashboard\Index remove the updateTasks method. 
Change your listener to:
```php
protected $listeners = [
        'confirmedDone',
        'cancelledDone',
        'updateTasks' => '$refresh',
    ];
```

Then in your modal:
```php
$this->closeModalWithEvents(['updateTasks']);
```

$refresh will cause the component to be refreshed without any other actions. Mount will be called on refresh so no need to duplicate pulling the tasks.

**Comment by alighasemzadeh** [comment]
@pwncraft 
Hi Thanks but It doesn't work well for me.

**Comment by pwncraft** [comment]
How so? What is happening?

**Comment by alighasemzadeh** [comment]
@pwncraft 
I can add but no refresh happen.
Amazing some actions not work well.

**Comment by pwncraft** [comment]
I cloned your repo.

First you need to wrap your livewire component in a single element. I just put a div around the two divs in your dashboard.index blade.

Second the event is working, I logged $this->tasks in the mount method. After creating a task it did not show up in the results in the log file. I was able to work around this by modifying your Index component:
```php
class Index extends Component
{
    public $task;
    public $tasks;

    protected $listeners = [
        'confirmedDone',
        'cancelledDone',
        'updateTasksList' => 'getTasks',
    ];

    public function mount()
    {
        $this->getTasks();
    }

    public function getTasks()
    {
        $this->tasks = Task::where('user_id', auth()->user()->id)->where('status', 'create')->latest()->get();
    }
```

Now the tasks refresh.

**Comment by PhiloNL** [comment]
Thanks for helping @pwncraft.
I don't have any issues with events so I think this issue is not related to the modal package as mentioned earlier.
