### ISSUE TITLE
Refreh or destroy child modal after submit?

### ISSUE THREAD

**Issue by seabasss** [livewire-ui/modal#83]
Is there a way to refresh/reset a child modal after it has been closed?

In your twitter video you click Create and add a policy. When you save, close the child modal and later click Create policy again, how do you start with a fresh policy page? I could manually reset the variables, but would love to refresh everything since I have js components that may stick even if the model is reset.

Thanks!

**Comment by PhiloNL** [comment]
It doesn't reset for me either. You could emit an event to reset the variable manually. 

It would be quite easy to achieve by unsetting the child modal from the main modal which is set in this array https://github.com/livewire-ui/modal/blob/main/src/Modal.php#L14

Feel free to create a PR that adds a `destroyComponent` event listener to https://github.com/livewire-ui/modal/blob/main/src/Modal.php that accepts the component name as a parameter and removes this component from the `$components` array.

This way you can do something like `$this->emit('destroyModal', CreateModal::getName());`. Once destroyed, a 'fresh' instance is loaded the next time.

An alternative, not nested, would be to pass some other unique value every:

<button wire:click='$emit("openModal", "create-policy", {{ json_encode([$user->id, Str::random()]) }})'>Create Policy</button>
<button wire:click='$emit("openModal", "create-policy", {{ json_encode([$user->id, Str::random()]) }})'>Create Policy</button>

The random value will create a different 'signature', so every child modal gets a different state.

**Comment by seabasss** [comment]
Thank you!

The `Str::random()` method sounds the easiest, but if I click on 'Create' and 'Cancel' to go back to the main modal over and over I'd get a bunch of hidden modals floating around right? May not be an issue since they're removed when I finally close, but just a thought.

**Comment by PhiloNL** [comment]
No worries. That's correct, you do end up with a bunch of hidden modals but I don't expect this to be an issue.

**Comment by danielreales7** [comment]
Hi @PhiloNL  How can I create the destroyModal method in your package without touching the original code?
I have a problem with the childs modals because when I open the first modal and close it, the data that I load in modal with alpine is keeping the DOM. 
![image](https://user-images.githubusercontent.com/5383214/133101934-657859c2-ae78-4e3e-8bd7-de2f94448b37.png)

I don´t know why...
