### ISSUE TITLE
publish modal.blade.php?

### ISSUE THREAD

**Issue by theoreaves** [livewire-ui/modal#88]
I would like to make a tweak to the (modal/resources/views/modal.blade.php) page, specifically, the styling.  However, I don't see any way to publish this file for that purpose. Is this possible?

(I'm kinda new to the laravel/composer world, so forgive me if this is something super simple)

**Comment by PhiloNL** [comment]
Hi @theoreaves 
You can use the publish command to publish the modal blade file:

```
php artisan vendor:publish --tag=livewire-ui-modal-views
```

**Comment by theoreaves** [comment]
Perfect!  That is exactly what I was looking for.  

Thanks!
