### ISSUE TITLE
Avoid opening multiple modals

### ISSUE THREAD

**Issue by labomatik** [livewire-ui/modal#90]
I have a button in a blade file that is triggering an event on a livewire that is triggering the opening of the modal.
If I click multiple times, the modal will be opened 2-3 times.

Is there a way to avoid the opening of the same modal with the same parameters?

**Comment by PhiloNL** [comment]
If the modal parameters are the same only one modal should open, for example, if I execute this 10 times in a row only one modal will open:
```
Livewire.emit("openModal", "edit-user", {"edit":"ad961710-9120-4099-9a7c-11e7e6ca7fec"});
```

**Comment by labomatik** [comment]
I've this:
`onclick="Livewire.emit('openModal', 'admin.master-search')"`
and clicking 3 times (quickly) on the same button is opening me 3 modals, only one is opened at a time but if i close one, the other one is displayed.

I tried to edit this line https://github.com/livewire-ui/modal/blob/0fe7036574868758f328e2266ecf27d3b30b7555/src/Modal.php#L33 by adding a check if $id is already in the component array and it is ok, only one modal is opened.
Can it be the fix?

**Comment by PhiloNL** [comment]
I'm unable to replicate this issue, I even did a network throttle and clicked the button 10 times.

`$this->components[$id]` already 'checks' if the id is already in the component array as it will simply overwrite the component with the same ID so only one can exist at any given time.

If I check the DOM I can only see one component as well:

![image](https://user-images.githubusercontent.com/1133950/135827256-ffdec73a-94c5-4dba-b396-d2ec0715e1cd.png)

If you have 2-3 modals in the DOM this means some value is unique every time you click the button which results in a different component id.

**Comment by labomatik** [comment]
Hello Phil,

here is a video of the issue, hope it will help.

https://user-images.githubusercontent.com/179987/135866850-35593d97-acd1-4de9-b26d-9059b7402519.mov

**Comment by PhiloNL** [comment]
Thanks for the video. Unfortunately, without any actual code, I'm unable to replicate this issue. If you can share some existing code you are using in the video, I can take another look.

**Comment by labomatik** [comment]
Strange, this is what is triggering the opening:
`<button wire:click="openNewBooking" class="ml-4 inline-block relative bg-rdv-blue p-1 rounded-full text-white hover:text-gray-100 hover:bg-rdv-blueribbon focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-rdv-blue">
            <span class="sr-only">{{ trans('rdv.nouveau_rendezvous') }}</span>
            <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"/>
            </svg>
        </button>`

livewire:
`public function openNewBooking(){
        $this->isLoading=true;
        $this->emit('openModal', 'admin.booking.create');
    }`
