### ISSUE TITLE
mhmiton/laravel-modules-livewire Support

### ISSUE THREAD

**Issue by aeq-dev** [livewire-ui/modal#99]
Hello;
I'm using this package [laravel-modules-livewire](https://github.com/mhmiton/laravel-modules-livewire) which is an extension for the package [laravel-modules](https://github.com/nWidart/laravel-modules)
This error appears :
```
Livewire\Exceptions\ComponentNotFoundException
Unable to find component: ['module_name'.path.to.component]

```
Any help please
Thanks.

**Comment by PhiloNL** [comment]
Please report your issue to https://github.com/mhmiton/laravel-modules-livewire or https://github.com/nWidart/laravel-modules

**Comment by aeq-dev** [comment]
Thanks.

**Comment by jcabanillas** [comment]
@aeq-dev do you find any solution to your problem?
